export const environment = {
  USER: process.env.PLAN_TRABAJO_DOCENTE_CRUD_USER,
  PASS: process.env.PLAN_TRABAJO_DOCENTE_CRUD_PASS,
  HOST: process.env.PLAN_TRABAJO_DOCENTE_CRUD_HOST,
  PORT: process.env.PLAN_TRABAJO_DOCENTE_CRUD_PORT,
  DB: process.env.PLAN_TRABAJO_DOCENTE_CRUD_DB,
  HTTP_PORT: process.env.PLAN_TRABAJO_DOCENTE_CRUD_HTTP_PORT,
  AUTH_DB: process.env.PLAN_TRABAJO_DOCENTE_CRUD_AUTH_DB,
};
